### ISSUE TITLE
Input addition issues (Please wait while...)

### ISSUE THREAD

**Issue by bedwards6954** [Cisco-AMP/amp4e_splunk_events_input#30]
I have the app installed on a heavy forwarder along with Syslog-ng. I have the credentials and API stuff configured correctly I can see my AMP4E groups, however when I go to save the new input the page just sits with please wait while we set up the amp for endpoints streaming resource. 
that's it no errors just sits, waited 30 min and nothing new.

**Comment by pschulze** [comment]
Hi @bedwards6954,
What version of Splunk are you running the app on?
Do you see any errors in `$SPLUNK_HOME/var/log/splunk/amp4e_events_input.log`?

**Comment by ladav9999** [comment]
I have the same problem on a heavy forwarder ver 7.3.4. Only logs in the amp4e_events_input.log are

INFO Amp4eEvents - Received response from ApiService (200)

**Comment by bedwards6954** [comment]
2020-02-13 17:13:38,752 ERROR Amp4eEvents - ConnectionError(MaxRetryError("HTTPS                    ConnectionPool(host='https', port=443): Max retries exceeded with url: //api.amp                    .cisco.com/v1/event_types/ (Caused by <class 'socket.gaierror'>: [Errno -2] Name                     or service not known)",),)
2020-02-13 17:13:38,753 ERROR Amp4eEvents - API Error (status 502): Request fail                    ure: <class 'requests.exceptions.ConnectionError'>
2020-02-13 17:14:30,633 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 3                    2, in wrapper
    response = func(*args, **kwargs)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 7                    2, in event_types
    return requests.get(self.__construct_url('', self.EVENT_TYPES_ENDPOINT), **s                    elf.__shared_options())
  File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 55, in ge                    t
    return request('get', url, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 44, in re                    quest
    return session.request(method=method, url=url, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 468,                     in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 571,                     in send
    r = adapter.send(request, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/adapters.py", line 375,                     in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceed                    ed with url: //api.amp.cisco.com/v1/event_types/ (Caused by <class 'socket.gaier                    ror'>: [Errno -2] Name or service not known)

2020-02-13 17:14:30,633 ERROR Amp4eEvents - ConnectionError(MaxRetryError("HTTPS                    ConnectionPool(host='https', port=443): Max retries exceeded with url: //api.amp                    .cisco.com/v1/event_types/ (Caused by <class 'socket.gaierror'>: [Errno -2] Name                     or service not known)",),)
2020-02-13 17:14:30,634 ERROR Amp4eEvents - API Error (status 502): Request fail                    ure: <class 'requests.exceptions.ConnectionError'>
2020-02-13 17:14:30,636 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 3                    2, in wrapper
    response = func(*args, **kwargs)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 7                    6, in groups
    return requests.get(self.__construct_url('', self.GROUPS_ENDPOINT), **self._                    _shared_options())
  File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 55, in ge                    t
    return request('get', url, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 44, in re                    quest
    return session.request(method=method, url=url, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 468,                     in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 571,                     in send
    r = adapter.send(request, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/adapters.py", line 375,                     in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceed                    ed with url: //api.amp.cisco.com/v1/groups/ (Caused by <class 'socket.gaierror'>                    : [Errno -2] Name or service not known)

**Comment by bedwards6954** [comment]
I fixed my connection issues
now I get
2020-02-13 18:17:32,349 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.ConnectionError'>
2020-02-13 18:18:10,119 INFO Amp4eEvents - Received response from ApiService (200)
2020-02-13 18:18:10,653 INFO Amp4eEvents - Received response from ApiService (200)

**Comment by bedwards6954** [comment]
this is what I get when I try to setup a new input

2020-02-13 18:24:07,751 INFO Amp4eEvents - Received response from ApiService (200)
2020-02-13 18:24:10,256 INFO Amp4eEvents - Received response from ApiService (200)
2020-02-13 18:24:10,288 INFO Amp4eEvents - Received response from ApiService (200)

**Comment by bedwards6954** [comment]
> I have the same problem on a heavy forwarder ver 7.3.4. Only logs in the amp4e_events_input.log are
> 
> INFO Amp4eEvents - Received response from ApiService (200)

did you happen to figure it out?

**Comment by bedwards6954** [comment]
Splunk Enterprise
Version:
7.3.3
Build:
7af3758d0d5e

CURRENT APPLICATION
Cisco AMP for Endpoints Events Input
Version:
1.1.7
Build:
10

**Comment by ladav9999** [comment]
> > I have the same problem on a heavy forwarder ver 7.3.4. Only logs in the amp4e_events_input.log are
> > INFO Amp4eEvents - Received response from ApiService (200)
> 
> did you happen to figure it out?

No, still having the same issue.

**Comment by setuparimi** [comment]
> I fixed my connection issues
> now I get
> 2020-02-13 18:17:32,349 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.ConnectionError'>
> 2020-02-13 18:18:10,119 INFO Amp4eEvents - Received response from ApiService (200)
> 2020-02-13 18:18:10,653 INFO Amp4eEvents - Received response from ApiService (200)

@bedwards6954 : Hey..how did you fix the connection issues by the way? I am facing the same issue, just curious. Was it an issue on the Splunk server end or the AMP?

**Comment by swati2121** [comment]
Hey,
I have been trying to integrate AMP for endpoints with Splunk that is hosted in our AWS. It's been over a month that i have facing this issue. I get the below error message:
INFO Amp4eEvents - Received response from ApiService (401)
2020-05-15 15:00:28,083 ERROR Amp4eEvents - API Error (status 401): {"version":null,"data":{},"errors":[{"error_co$
The message indicates that there is issue with API credentials but even after using different set of API credentials and that too with different permissions(read/write or read only) we experience the same issue. The splunk UI keeps freezing and keeps telling us to wait till the configuration is being saved.
Is anybody facing the same issue? Please reach out.

**Comment by pschulze** [comment]
Hi @swati2121, if you're receiving a 401 code from the API that indicates that your credentials are invalid. Please make sure that the credentials that you're inputting in Splunk match those generated on the AMP console, and that those credentials have both read and write permissions.

**Comment by swati2121** [comment]
> Hi @swati2121, if you're receiving a 401 code from the API that indicates that your credentials are invalid. Please make sure that the credentials that you're inputting in Splunk match those generated on the AMP console, and that those credentials have both read and write permissions.

Hey @pschulze. Thank you for reaching out. I am using the same API key that has been generated from the AMP console. I also tried another API key with different permission and got the same issue. The weird thing is that i reached out to Cisco AMP support and they tried to re create the issue. They also experienced the same issue. That Cisco's engineer used the same steps i used for integration.

**Comment by l08uk0** [comment]
> > I fixed my connection issues
> > now I get
> > 2020-02-13 18:17:32,349 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.ConnectionError'>
> > 2020-02-13 18:18:10,119 INFO Amp4eEvents - Received response from ApiService (200)
> > 2020-02-13 18:18:10,653 INFO Amp4eEvents - Received response from ApiService (200)
> 
> @bedwards6954 : Hey..how did you fix the connection issues by the way? I am facing the same issue, just curious. Was it an issue on the Splunk server end or the AMP?

Hi @bedwards6954, I am also interested on knowing how did you fix the connectivity issues, as I have the same error logs.
I can ping the AMP server.

Thanks in advance

**Comment by l08uk0** [comment]
> > I fixed my connection issues
> > now I get
> > 2020-02-13 18:17:32,349 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.ConnectionError'>
> > 2020-02-13 18:18:10,119 INFO Amp4eEvents - Received response from ApiService (200)
> > 2020-02-13 18:18:10,653 INFO Amp4eEvents - Received response from ApiService (200)
> 
> @bedwards6954 : Hey..how did you fix the connection issues by the way? I am facing the same issue, just curious. Was it an issue on the Splunk server end or the AMP?

Have you gotten the solution to his?

**Comment by lznger88** [comment]
Has anyone managed to resolve this? I'm having the same issue using the latest Splunk version and newest app version 2.0.1. When I try and save the new input, it just sits on the page saying 'Please wait while we setup the AMP for Endpoints streaming resource...'

Connection works '2021-03-22 14:59:47,165 INFO Amp4eEvents - Received response from ApiService (200)' and I can curl all information, tested using /v1/events. I have even disabled handshake in base.connections.py

**Comment by samsonnguyen** [comment]
https://splunkbase.splunk.com/app/3670

please try again with v2.0.2 of the app
