### ISSUE TITLE
Can't connect to cisco amp using the endpoint app for splunk

### ISSUE THREAD

**Issue by barakat-abweh** [Cisco-AMP/amp4e_splunk_events_input#9]
Each time I try to connect to cisco amp using the endpoint app for splunk it fails, the error says 
" Warning! We couldn’t retrieve the information from API with provided credentials. Please make sure the API host is accessible or re-configure the input with correct credentials. "
I've tested the credentials in the command line terminal and it gave results, but with splunk it keeps giving the above error.
my configurations are like the following
AMP for Endpoints API Host *
api.eu.amp.cisco.com
 API Client ID * 
my-id
 API Key * 
my-key
any help to make it work???

**Comment by inspired** [comment]
I see that you closed this issue. Would you care to explain how you resolved it? I am getting the exact same warning as you got, also connecting to api.eu.amp.cisco.com. Splunk 7.2.3

$SPLUNK_HOME/var/log/splunk/amp4e_events_input.log shows the following

> 2019-04-30 21:15:24,039 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-04-30 21:15:24,039 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>
2019-04-30 21:15:24,040 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 31, in wrapper
    response = func(*args, **kwargs)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 71, in event_types
    return requests.get(self.__construct_url('', self.EVENT_TYPES_ENDPOINT), **self.__shared_options())
  File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory
2019-04-30 21:15:24,040 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-04-30 21:15:24,041 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>

**Comment by barakat-abweh** [comment]
@inspired  you need to whitelist the domains on your firewall

**Comment by inspired** [comment]
Hi,

Port 443 outbound is open through the firewall. I have tested with curl and
OpenSSL from the Splunk server, so that is not the issue.



søn. 5. mai 2019, 10:26 skrev Barakat Abweh <notifications@github.com>:

**Comment by barakat-abweh** [comment]
Dear @inspired, this was my case and i used to use curl and wget to get the data and it was working perfectly but when using the app nothing was working until we whitelisted the domains

**Comment by inspired** [comment]
Thanks for the pointers :-)

I'll open a separate issue as it seems I am experiencing a different
problem.

What Splunk version were you using, by the way?

søn. 5. mai 2019, 10:55 skrev Barakat Abweh <notifications@github.com>:
